name: Workflow
on:
  push:
    branches:
      - QA
  schedule:
      - cron: '05 15 * * *'
jobs:
  simple_test:
    runs-on: ubuntu-latest
    steps:
      - name: bonjour
        run: echo "Hello world 05 15 * * *"
